--Beatriz Falasca Lopes da Silva     RM 570086
--Felipe Ramos Lessa                 RM 570626
--Gabriel Rodrigues Costa            RM 568762
--Gabrielle Trindade Ferreira        RM 569092
--Maria Eduarda Rodrigues da Silva   RM 572951


/*
DROP TABLE "T_PRONTUARIOS" CASCADE CONSTRAINTS;
*/


--------------------------------------------------------
--  DDL for Table T_PRONTUARIOS
--------------------------------------------------------

  CREATE TABLE "T_PRONTUARIOS" 
   (	"ID_PACIENTE" NUMBER(5,0), 
	"IDADE" NUMBER(3,0), 
	"SEXO" CHAR(1 BYTE), 
	"ID_INTERNACAO" NUMBER(5,0), 
	"MUNICIPIO_REGIAO_DE_RESIDENCIA" VARCHAR2(15 BYTE), 
	"DATA_DE_INTERNACAO" DATE, 
	"DATA_DE_SAIDA" VARCHAR2(15 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"TEMPO_DE_PERMANENCIA_DIAS" NUMBER(2,0), 
	"TIPO_DE_INTERNACAO" VARCHAR2(20 BYTE), 
	"NOME_DO_HOSPITAL" VARCHAR2(60 BYTE), 
	"ID_DO_HOSPITAL" NUMBER(6,0), 
	"NIVEL_DE_ATENCAO" VARCHAR2(25 BYTE), 
	"REGIAO_DO_HOSPITAL" VARCHAR2(25 BYTE), 
	"SETOR_UNIDADE" VARCHAR2(25 BYTE), 
	"DOENCA_DETECTADA" VARCHAR2(60 BYTE), 
	"CID" VARCHAR2(25 BYTE), 
	"VALOR_DIARIA_LEITO" VARCHAR2(15 BYTE), 
	"NUMERO_TOTAL_DE_LEITOS_INSTALADOS" NUMBER(3,0), 
	"NUMERO_DE_LEITOS_OCUPADOS" NUMBER(3,0), 
	"NUMERO_DE_LEITOS_DISPONIVEIS" NUMBER(3,0), 
	"FC" NUMBER(3,0), 
	"FR" NUMBER(3,0), 
	"PAS" NUMBER(3,0), 
	"TEMP_AXILAR" NUMBER(5,1), 
	"SPO2" NUMBER(2,0), 
	"NIVEL_DE_CONSCIENCIA" NUMBER(2,0), 
	"DIURESE" NUMBER(5,2), 
	"GLICEMIA_CAPILAR" NUMBER(3,0), 
	"SONDA_VESICAL_DE_DEMORA" VARCHAR2(3 BYTE), 
	"SONDA_NASOGASTRICA" VARCHAR2(3 BYTE), 
	"SONDA_NASOENTERAL" VARCHAR2(3 BYTE), 
	"CATETER_DE_O2" VARCHAR2(3 BYTE), 
	"INTUBACAO_OROTRAQUEAL" VARCHAR2(3 BYTE), 
	"VENTILACAO_MECANICA" VARCHAR2(3 BYTE), 
	"CATETER_VENOSO_CENTRAL" VARCHAR2(3 BYTE), 
	"CATETER_VENOSO_CENTRAL_DE_INSERCAO_PERIFERICA_PICC" VARCHAR2(3 BYTE), 
	"CATETER_VENOSO_PERIFERICO" VARCHAR2(3 BYTE), 
	"TC_POSITIVO_PARA_AVC" VARCHAR2(3 BYTE), 
	"EEG_POSITIVO_PARA_AVC" VARCHAR2(3 BYTE), 
	"VACINA_INFLUENZA" VARCHAR2(3 BYTE), 
	"VACINA_COVID" VARCHAR2(3 BYTE), 
	"HIPERTENSAO" VARCHAR2(3 BYTE), 
	"DIABETES" VARCHAR2(3 BYTE), 
	"SEQUELA_DE_AVC" VARCHAR2(3 BYTE), 
	"FIBRILACAO_ATRIAL" VARCHAR2(3 BYTE), 
	"INSUFICIENCIA_CARDIACA" VARCHAR2(3 BYTE), 
	"DRC" VARCHAR2(3 BYTE), 
	"OBESIDADE" VARCHAR2(3 BYTE), 
	"NEOPLASIA" VARCHAR2(3 BYTE), 
	"ANTIBIOTICO" VARCHAR2(5 BYTE), 
	"DATA_DE_INICIO_ATB" VARCHAR2(10 BYTE), 
	"DURACAO_ATB" VARCHAR2(5 BYTE), 
	"PADRAO_TOMOGRAFIA" VARCHAR2(80 BYTE), 
	"ETIOLOGIA_PNEUMONIA" VARCHAR2(30 BYTE), 
	"TRATAMENTO_ETIOLOGICO" VARCHAR2(80 BYTE), 
	"DPOC" VARCHAR2(5 BYTE), 
	"DEMENCIA_ALZHEIMER" VARCHAR2(5 BYTE), 
	"UROCULTURA" VARCHAR2(80 BYTE), 
	"HPB" VARCHAR2(5 BYTE), 
	"LITIASE_URINARIA" VARCHAR2(5 BYTE), 
	"LEITOS_OCUPADOS_OUTRAS_DOENCAS" NUMBER(3,0), 
	"LEITOS_DESTINADOS_AVC_ITU_PNEUMONIA" NUMBER(3,0), 
	"TAXA_OCUPACAO_AVC_ITU_PNEUMONIA" NUMBER(5,4)
   );

   COMMENT ON COLUMN "T_PRONTUARIOS"."ID_PACIENTE" IS 'Identificador do paciente presente no dataset de origem.';
   COMMENT ON COLUMN "T_PRONTUARIOS"."ID_INTERNACAO" IS 'Identificador da internação hospitalar presente no dataset de origem.';
   COMMENT ON COLUMN "T_PRONTUARIOS"."STATUS" IS 'Situação ou desfecho registrado para a internação, como internado, alta ou óbito.';
   COMMENT ON COLUMN "T_PRONTUARIOS"."ID_DO_HOSPITAL" IS 'Identificador do hospital responsável pela internação no dataset de origem.';
   COMMENT ON COLUMN "T_PRONTUARIOS"."DOENCA_DETECTADA" IS 'Diagnóstico principal associado à internação hospitalar no dataset sintético.';
   COMMENT ON COLUMN "T_PRONTUARIOS"."CID" IS 'Código CID-10 associado ao diagnóstico principal da internação.';
   COMMENT ON TABLE "T_PRONTUARIOS"  IS 'Tabela de staging do DataCross contendo os dados sintéticos originalmente importados do dataset hospitalar.';
--------------------------------------------------------
--  DDL for Index T_PRONTUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "T_PRONTUARIOS_PK" ON "T_PRONTUARIOS" ("ID_INTERNACAO");
--------------------------------------------------------
--  Constraints for Table T_PRONTUARIOS
--------------------------------------------------------

  ALTER TABLE "T_PRONTUARIOS" ADD CONSTRAINT "T_PRONTUARIOS_PK" PRIMARY KEY ("ID_INTERNACAO");
